# Generated by Django 4.1.5 on 2023-01-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_booking_booking_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booking_datetime', 'table_no')},
        ),
    ]
